$schema: http://json-schema.org/draft-04/schema#
id: project
title: project
type: object
namespace: http://192.168.0.230/
category: administrative
program: '*'
project: '*'
description: the sub project within a given program
submittable: true
validators: null
systemProperties:
- id
- project_id
- state
- created_datetime
- updated_datetime
uniqueKeys:
- - id
- - project_id
  - submitter_id
required:
- submitter_id
- type
links:
- name: programs
  backref: projects
  label: part_of
  target_type: program
  multiplicity: one_to_many
  required: true
properties:
  $ref: _definitions.yaml#/ubiquitous_properties
  availability_type:
    type: string
    description: the hardcoded availability type
  dbgap_accession_number:
    type: string
    description: the db gap accession number
  node_name:
    type: string
    description: the name of the node in the database
  data_submitter_id:
    type: string
    description: a human-readable unique identifier for a record in the metadata database
  code:
    type: string
    description: unique identifier for the project
  program_name:
    type: string
    description: the program the data source belongs to; the parent node
  project_name:
    type: string
    description: the name of the project
  location:
    type: string
    description: the location of the project
  collaborators:
    type: array
    items:
      type: string
    description: List of collaborators
  contributor:
    type: string
    description: ''
  programs:
    $ref: _definitions.yaml#/to_many
additionalProperties: false
